version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
    - "16686:16686"
    - "14250:14250"
  prometheus:
    image: prom/prometheus:v2.33.4
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus:/etc/prometheus
    - prometheus-data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    depends_on:
    - otel-collector
  otel-collector:
    image: otel/opentelemetry-collector:0.45.0
    command: ["--config=/etc/otel-collector/config.yml"]
    volumes:
    - ./collector:/etc/otel-collector
    ports:
    - "4317:4317" # gRPC receiver
    - "8888:8888" # Prometheus metrics exposed by the collector
    - "8889:8889" # Prometheus exporter metrics
    depends_on:
    - jaeger
  fib:
    build:
      context: ../
      dockerfile: example/Dockerfile
    ports:
    - "41820:41820"
    environment:
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
    - otel-collector

volumes:
  prometheus-data:
